# Generated by Django 4.2 on 2023-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_activity', models.CharField(max_length=255)),
                ('user_date_registration', models.DateField(auto_now_add=True)),
                ('user_access', models.BooleanField(default=True)),
            ],
        ),
    ]
